version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.14
      environment:
        GO111MODULE: "on"
    working_directory: /go/src/github.com/granular-oss/terraform-provider-credstash
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-mod-v1-{{ checksum "go.sum" }}
        - go-mod-v1-
    - run: go test ./...
    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
        - /go/pkg/mod
